// import Link from "next/link"


// export default function About() {
//     return (
//         <> About page </>
//     )
// }

// <main> 

//     <div className={styles.grid}>
        
//     <Link href='/'>
//        <button>Go Back </button> 
//     </Link>
//     </div>

// </main>

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Example #1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
    

      <Link href='/'>
        <button>Go Back </button> 
     </Link>

      
      </main>
    </>
  
  )}
